### ISSUE TITLE
Add player input map as a property

### ISSUE THREAD

**Issue by manuq** [endlessm/moddable-platformer#8]
In the moddable platformer, it should be possible to choose whether a Player node is controlled using the WASD keys, or arrow keys. We may need to change the input map slightly to support two player mode, or perhaps add a third option which is designed for a single player game.

While we're here, we should add our own input map instead of using the built in "ui_accept" / "ui_left" / "ui_right" actions.

**Comment by wjt** [comment]
Implemented by 4bbcc302b4b46081f6cb9ad07af826234c2998d0.
